# Logic gates with Neural Networks (Backpropogation)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('max_colwidth', None)

In [2]:
def sigmoid(x):
    """Implementing the sigmoid function for x.
    sig(x) = 1/(1+e^-x)

    Args:
        x: input for which signmoid function needs to be calculated.

    Returns:
        the sigmoid function.
    """
    return 1 / (1 + (np.exp(-x)))

In [3]:
def sigmoid_derivative(x):
    """Implementing the sigmoid function for x.
    sig'(x) = x * (1-x)

    Args:
        x: input for which derivative of signmoid function needs to be calculated.

    Returns:
        the derivative of sigmoid function.
    """
    return sigmoid(x) * (1-sigmoid(x))

## Setting input, `X` and output, `Y_target`

In [4]:
# set the Input datasets
X = np.array([[0,0],[0,1],[1,0],[1,1]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
outputs = {
    'and': [[0], [0], [0], [1]], 'nand': [[1], [1], [1], [0]], 'or': [[0], [1], [1], [1]],
    'nor': [[1], [0], [0], [0]], 'xor': [[0], [1], [1], [0]], 'xnor': [[1], [0], [0], [1]]
}

lg = """
█░░ █▀▀█ █▀▀▀ ░▀░ █▀▀ 　 █▀▀▀ █▀▀█ ▀▀█▀▀ █▀▀ █▀▀ 
█░░ █░░█ █░▀█ ▀█▀ █░░ 　 █░▀█ █▄▄█ ░░█░░ █▀▀ ▀▀█ 
▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀ ▀▀▀ 　 ▀▀▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀▀▀
A B | AND NAND OR NOR XOR XNOR
-------------------------------
0 0 |  0    1   0  1   0   1
0 1 |  0    1   1  0   1   0
1 0 |  0    1   1  0   1   0
1 1 |  1    0   1  0   0   1
"""
print(lg)

while True:
    try:
        output_gate = input('Enter your chosen logic gate: ').lower()
        break
    except KeyError:
        print('Invalid logic gate, try again!\n')

# set the expected output
Y_target = np.array(outputs[output_gate])
Y_target


█░░ █▀▀█ █▀▀▀ ░▀░ █▀▀ 　 █▀▀▀ █▀▀█ ▀▀█▀▀ █▀▀ █▀▀ 
█░░ █░░█ █░▀█ ▀█▀ █░░ 　 █░▀█ █▄▄█ ░░█░░ █▀▀ ▀▀█ 
▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀ ▀▀▀ 　 ▀▀▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀▀▀
A B | AND NAND OR NOR XOR XNOR
-------------------------------
0 0 |  0    1   0  1   0   1
0 1 |  0    1   1  0   1   0
1 0 |  0    1   1  0   1   0
1 1 |  1    0   1  0   0   1

Enter your chosen logic gate: xor


array([[0],
       [1],
       [1],
       [0]])

## Training

In [6]:
# assigning random weights
# 6 for hidden layer
# 3 for output layer
W1 = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
W2 = np.array([[0.7], [0.8], [0.9]])
initial_W1 = W1.copy()
initial_W2 = W2.copy()

# learning rate
lr = 0.05
print("\nLearning rate:", lr)
print('\n')

for epoch in range(100000):
    # forward propagation
    Z = np.dot(X, W1)
    H = sigmoid(Z)

    U = np.dot(H, W2)
    Y = sigmoid(U)

    # calculate Loss function (Mean Square error loss)
    E = abs(Y - Y_target)
    L = 1/2 * (np.power(E, 2))

    # backpropagation - Stage 1
    dL_dY = Y - Y_target
    dY_dU = Y * (1-Y)
    dU_dW2 = H

    dL_dW2 = np.dot(dU_dW2.T,dL_dY*dY_dU)

    # weight updates in stage 1
    W2 -= lr*dL_dW2

    # backpropagation - Stage 2
    dL_dY = Y-Y_target
    dY_dU = Y*(1-Y)
    dU_dH = W2
    dH_dZ = H*(1-H)
    dZ_dW1 = X

    dL_dH = np.dot(dL_dY*dY_dU,dU_dH.T)
    dL_dW1 = np.dot(dZ_dW1.T,dH_dZ*dL_dH)

    # weight updates in stage 2
    W1 -= lr*dL_dW1

    if epoch % 10000 == 0:
        print("%6d -   %5s: %.4f    %8s: %.4f" % (epoch, 'Error', E.sum(), 'MSE loss', L.sum()))


Learning rate: 0.05


     0 -   Error: 1.9948    MSE loss: 0.6814
 10000 -   Error: 1.9623    MSE loss: 0.4827
 20000 -   Error: 0.6474    MSE loss: 0.0525
 30000 -   Error: 0.2925    MSE loss: 0.0114
 40000 -   Error: 0.2209    MSE loss: 0.0067
 50000 -   Error: 0.1850    MSE loss: 0.0048
 60000 -   Error: 0.1623    MSE loss: 0.0037
 70000 -   Error: 0.1464    MSE loss: 0.0031
 80000 -   Error: 0.1343    MSE loss: 0.0026
 90000 -   Error: 0.1248    MSE loss: 0.0023


In [7]:
print("INITIAL WEIGHTS")
print("1:\n", initial_W1)
print("2:\n", initial_W2)

print("\n\nFINAL WEIGHTS")
print("1:\n", W1)
print("2:\n", W2)

INITIAL WEIGHTS
1:
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
2:
 [[0.7]
 [0.8]
 [0.9]]


FINAL WEIGHTS
1:
 [[-3.47262741  5.84327708  5.58573629]
 [ 5.82108732 -3.48158799  5.60605559]]
2:
 [[-9.88564386]
 [-9.88112613]
 [13.71452502]]


## Testing

In [8]:
z_vals = []
h_vals = []
u_vals = []
y_vals = []
preds = []

for point in X:
    point = np.array(point)
    z = np.dot(point, W1)
    z_vals.append(z)

    h = sigmoid(z)
    h_vals.append(h)

    op = np.dot(h, W2)
    u_vals.append(op)

    y_cap = sigmoid(op)
    y_vals.append(y_cap)

    preds.append(y_cap[0])

print(f"LOGIC GATE: {output_gate.upper()}")
pd.DataFrame.from_dict({
    'Input1': X.reshape(-1)[::2],
    'Input2': X.reshape(-1)[1::2],
    'Z': z_vals,
    'H': h_vals,
    'U': u_vals,
    'Y': y_vals,
    'Target': Y_target.reshape(-1),
    'Prediction': preds
})

LOGIC GATE: XOR


Input1  Input2  \
0       0       0   
1       0       1   
2       1       0   
3       1       1   

                                                             Z  \
0                                              [0.0, 0.0, 0.0]   
1  [5.821087321822066, -3.4815879859535985, 5.606055594599564]   
2  [-3.472627411902598, 5.8432770816353345, 5.585736287672163]   
3  [2.3484599099194683, 2.361689095681736, 11.191791882271726]   

                                                               H  \
0                                                [0.5, 0.5, 0.5]   
1  [0.9970443814205019, 0.02984067294193037, 0.9963379214939381]   
2   [0.03010117916010535, 0.997109056074629, 0.9962630303769473]   
3   [0.9128117351255599, 0.9138588655176287, 0.9999862132926991]   

                       U                      Y  Target  Prediction  
0  [-3.0261224827327133]  [0.04625960107200431]       0    0.046260  
1   [3.5130162329179386]   [0.9710558600991511]       1    0.971056  
2   [3.5131443745891717]   [0.9710594614798382]       1    0.971059  
3   [-4.339350493931107]  [0.01287701758602339]       0    0.012877