# Matrix operations
In machine learning, matrix operations are fundamental for various tasks such as data manipulation, transformations, and computations. They enable efficient handling of large datasets and complex mathematical operations that are essential for training and deploying machine learning models. Understanding matrix operations is crucial for implementing algorithms like linear regression, neural networks, and more, as they often involve operations like matrix multiplication, transposition, and inversion. Mastery of these operations allows for optimized performance and scalability in machine learning applications.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 1], [3, 4, 2], [4, 7, 8]])

## Matrix addition and subtraction
Matrix addition is where two matrices of the same dimensions are added together by adding their corresponding elements.

Matrix subtraction is where two matrices of the same dimensions are subtracted by subtracting their corresponding elements.

In machine learning, matrix addition is often used in various algorithms and models, such as neural networks, where weights and biases are updated during training. It allows for efficient manipulation of data and parameters, enabling the combination of different features or datasets. Understanding matrix addition is crucial for implementing and optimizing machine learning algorithms, as it plays a key role in operations like gradient descent and backpropagation.

In [12]:
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

A_plus_B = A + B
print("\nA + B:\n", A_plus_B)

A_minus_B = A - B
print("\nA - B:\n", A_minus_B)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[1 2 1]
 [3 4 2]
 [4 7 8]]

A + B:
 [[ 2  4  4]
 [ 7  9  8]
 [11 15 17]]

A - B:
 [[0 0 2]
 [1 1 4]
 [3 1 1]]


## Element-wise multiplication and division
Element-wise multiplication (Hadamard product) is where two matrices of the same dimensions are multiplied together by multiplying their corresponding elements.

Element-wise division is where two matrices of the same dimensions are divided by dividing their corresponding elements.

In machine learning, element-wise multiplication and division are essential for various operations, such as applying activation functions, normalizing data, and performing feature scaling. These operations allow for efficient manipulation of data at the individual element level, enabling models to learn complex patterns and relationships within the data. Understanding element-wise operations is crucial for implementing and optimizing machine learning algorithms, as they often involve operations like dropout in neural networks and feature-wise transformations.

In [15]:
# Element wise multiplication of A and B
A_times_B = np.multiply(A, B)
print("\nA * B:\n", A_times_B)

A_div_B = np.divide(A, B)
print("\nA / B:\n", A_div_B)


A * B:
 [[ 1  4  3]
 [12 20 12]
 [28 56 72]]

A / B:
 [[1.         1.         3.        ]
 [1.33333333 1.25       3.        ]
 [1.75       1.14285714 1.125     ]]


## Matrix multiplication
Matrix multiplication (dot product) is where two matrices are multiplied together by taking the sum of the products of the corresponding elements from the rows of the first matrix and the columns of the second matrix.

In machine learning, matrix multiplication is a fundamental operation used in various algorithms and models, such as linear regression, neural networks, and support vector machines. It enables the transformation of input data through layers of weights and biases, allowing models to learn complex relationships and patterns. Efficient matrix multiplication is crucial for handling large datasets and high-dimensional feature spaces, making it a key component in training and deploying machine learning models. Understanding matrix multiplication is essential for implementing and optimizing these algorithms effectively.

In [ ]:
A_dot_B = np.dot(A, B)
print("\nA . B (Matrix Multiplication):\n", A_dot_B)

# With PyTorch (more about pytorch in next notebook)
A_torch = torch.tensor(A)
B_torch = torch.tensor(B)
A_dot_B_torch = torch.matmul(A_torch, B_torch)
# alternatively: A_dot_B_torch = A_torch @ B_torch
print("\nA . B with PyTorch:\n", A_dot_B_torch)


A . B (Matrix Multiplication):
 [[ 19  31  29]
 [ 43  70  62]
 [ 67 109  95]]

A . B with PyTorch:
 tensor([[ 19,  31,  29],
        [ 43,  70,  62],
        [ 67, 109,  95]], dtype=torch.int32)
