In [1]:
import numpy as np
import pandas as pd

## Matrix manipulation

In [2]:
# Print A
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Print B
B = np.array([[1, 2, 0], [3, 4, 2], [4, 7, 8]])
B

array([[1, 2, 0],
       [3, 4, 2],
       [4, 7, 8]])

In [4]:
# Addition A+B
print('A + B =')
np.add(A, B)

A + B =


array([[ 2,  4,  3],
       [ 7,  9,  8],
       [11, 15, 17]])

In [5]:
# Subtraction A-B
print('A - B =')
np.subtract(A, B)

A - B =


array([[0, 0, 3],
       [1, 1, 4],
       [3, 1, 1]])

In [6]:
# Subtraction B-A
print('B - A =')
np.subtract(B, A)

B - A =


array([[ 0,  0, -3],
       [-1, -1, -4],
       [-3, -1, -1]])

In [7]:
# Element wise multiplication of A and B
print('A * B = ')
np.multiply(A, B)

A * B = 


array([[ 1,  4,  0],
       [12, 20, 12],
       [28, 56, 72]])

In [10]:
# Matrix multiplication
print('A.B =')
np.dot(A, B)

A.B =


array([[ 19,  31,  28],
       [ 43,  70,  58],
       [ 67, 109,  88]])

In [8]:
# Transpose of A
print('A transpose')
A.transpose()

A transpose


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
# Transpose of B
print('B transpose')
B.transpose()

B transpose


array([[1, 3, 4],
       [2, 4, 7],
       [0, 2, 8]])

In [11]:
# display first 2 columns
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [12]:
# display last 2 rows of last 2 columns of A
A[1:, 1:]

array([[5, 6],
       [8, 9]])

## Dataframes

### Cars dataset

In [13]:
cars = pd.read_csv('CarPrice_1.csv', index_col=0)
cars

symboling                   CarName fueltype aspiration doornumber  \
car_ID                                                                       
1               3        alfa-romero giulia      gas        std        two   
2               3       alfa-romero stelvio      gas        std        two   
3               1  alfa-romero Quadrifoglio      gas        std        two   
4               2               audi 100 ls      gas        std       four   
5               2                audi 100ls      gas        std       four   
...           ...                       ...      ...        ...        ...   
201            -1           volvo 145e (sw)      gas        std       four   
202            -1               volvo 144ea      gas      turbo       four   
203            -1               volvo 244dl      gas        std       four   
204            -1                 volvo 246   diesel      turbo       four   
205            -1               volvo 264gl      gas      turbo       four   

            carbody drivewheel enginelocation  wheelbase  carlength  ...  \
car_ID                                                               ...   
1       convertible        rwd          front       88.6      168.8  ...   
2       convertible        rwd          front       88.6      168.8  ...   
3         hatchback        rwd          front       94.5      171.2  ...   
4             sedan        fwd          front       99.8      176.6  ...   
5             sedan        4wd          front       99.4      176.6  ...   
...             ...        ...            ...        ...        ...  ...   
201           sedan        rwd          front      109.1      188.8  ...   
202           sedan        rwd          front      109.1      188.8  ...   
203           sedan        rwd          front      109.1      188.8  ...   
204           sedan        rwd          front      109.1      188.8  ...   
205           sedan        rwd          front      109.1      188.8  ...   

        enginesize  fuelsystem  boreratio stroke compressionratio  horsepower  \
car_ID                                                                          
1              130        mpfi       3.47   2.68              9.0         111   
2              130        mpfi       3.47   2.68              9.0         111   
3              152        mpfi       2.68   3.47              9.0         154   
4              109        mpfi       3.19   3.40             10.0         102   
5              136        mpfi       3.19   3.40              8.0         115   
...            ...         ...        ...    ...              ...         ...   
201            141        mpfi       3.78   3.15              9.5         114   
202            141        mpfi       3.78   3.15              8.7         160   
203            173        mpfi       3.58   2.87              8.8         134   
204            145         idi       3.01   3.40             23.0         106   
205            141        mpfi       3.78   3.15              9.5         114   

       peakrpm  citympg  highwaympg    price  
car_ID                                        
1         5000       21          27  13495.0  
2         5000       21          27  16500.0  
3         5000       19          26  16500.0  
4         5500       24          30  13950.0  
5         5500       18          22  17450.0  
...        ...      ...         ...      ...  
201       5400       23          28  16845.0  
202       5300       19          25  19045.0  
203       5500       18          23  21485.0  
204       4800       26          27  22470.0  
205       5400       19          25  22625.0  

[205 rows x 25 columns]

In [14]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 205 entries, 1 to 205
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   symboling         205 non-null    int64  
 1   CarName           205 non-null    object 
 2   fueltype          205 non-null    object 
 3   aspiration        205 non-null    object 
 4   doornumber        205 non-null    object 
 5   carbody           205 non-null    object 
 6   drivewheel        205 non-null    object 
 7   enginelocation    205 non-null    object 
 8   wheelbase         205 non-null    float64
 9   carlength         205 non-null    float64
 10  carwidth          205 non-null    float64
 11  carheight         205 non-null    float64
 12  curbweight        205 non-null    int64  
 13  enginetype        205 non-null    object 
 14  cylindernumber    205 non-null    object 
 15  enginesize        205 non-null    int64  
 16  fuelsystem        205 non-null    object 
 1

In [15]:
for col in cars.columns:
    print('Number of unique values for %16s  : %3d' %(col, cars[col].nunique()))

Number of unique values for        symboling  :   6
Number of unique values for          CarName  : 147
Number of unique values for         fueltype  :   2
Number of unique values for       aspiration  :   2
Number of unique values for       doornumber  :   2
Number of unique values for          carbody  :   5
Number of unique values for       drivewheel  :   3
Number of unique values for   enginelocation  :   2
Number of unique values for        wheelbase  :  53
Number of unique values for        carlength  :  75
Number of unique values for         carwidth  :  44
Number of unique values for        carheight  :  49
Number of unique values for       curbweight  : 171
Number of unique values for       enginetype  :   7
Number of unique values for   cylindernumber  :   7
Number of unique values for       enginesize  :  44
Number of unique values for       fuelsystem  :   8
Number of unique values for        boreratio  :  38
Number of unique values for           stroke  :  37
Number of un

In [16]:
cars = cars.drop(columns='price', index=range(100,150))
cars

symboling                   CarName fueltype aspiration doornumber  \
car_ID                                                                       
1               3        alfa-romero giulia      gas        std        two   
2               3       alfa-romero stelvio      gas        std        two   
3               1  alfa-romero Quadrifoglio      gas        std        two   
4               2               audi 100 ls      gas        std       four   
5               2                audi 100ls      gas        std       four   
...           ...                       ...      ...        ...        ...   
201            -1           volvo 145e (sw)      gas        std       four   
202            -1               volvo 144ea      gas      turbo       four   
203            -1               volvo 244dl      gas        std       four   
204            -1                 volvo 246   diesel      turbo       four   
205            -1               volvo 264gl      gas      turbo       four   

            carbody drivewheel enginelocation  wheelbase  carlength  ...  \
car_ID                                                               ...   
1       convertible        rwd          front       88.6      168.8  ...   
2       convertible        rwd          front       88.6      168.8  ...   
3         hatchback        rwd          front       94.5      171.2  ...   
4             sedan        fwd          front       99.8      176.6  ...   
5             sedan        4wd          front       99.4      176.6  ...   
...             ...        ...            ...        ...        ...  ...   
201           sedan        rwd          front      109.1      188.8  ...   
202           sedan        rwd          front      109.1      188.8  ...   
203           sedan        rwd          front      109.1      188.8  ...   
204           sedan        rwd          front      109.1      188.8  ...   
205           sedan        rwd          front      109.1      188.8  ...   

        cylindernumber  enginesize  fuelsystem boreratio stroke  \
car_ID                                                            
1                 four         130        mpfi      3.47   2.68   
2                 four         130        mpfi      3.47   2.68   
3                  six         152        mpfi      2.68   3.47   
4                 four         109        mpfi      3.19   3.40   
5                 five         136        mpfi      3.19   3.40   
...                ...         ...         ...       ...    ...   
201               four         141        mpfi      3.78   3.15   
202               four         141        mpfi      3.78   3.15   
203                six         173        mpfi      3.58   2.87   
204                six         145         idi      3.01   3.40   
205               four         141        mpfi      3.78   3.15   

        compressionratio horsepower  peakrpm  citympg  highwaympg  
car_ID                                                             
1                    9.0        111     5000       21          27  
2                    9.0        111     5000       21          27  
3                    9.0        154     5000       19          26  
4                   10.0        102     5500       24          30  
5                    8.0        115     5500       18          22  
...                  ...        ...      ...      ...         ...  
201                  9.5        114     5400       23          28  
202                  8.7        160     5300       19          25  
203                  8.8        134     5500       18          23  
204                 23.0        106     4800       26          27  
205                  9.5        114     5400       19          25  

[155 rows x 24 columns]

### Heart dataset

In [17]:
heart = pd.read_csv('Heart.csv')
heart

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [18]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [19]:
for col in heart.columns:
    print('Number of unique values for %10s  : %3d' %(col, heart[col].nunique()))

Number of unique values for        age  :  41
Number of unique values for        sex  :   2
Number of unique values for         cp  :   4
Number of unique values for   trestbps  :  49
Number of unique values for       chol  : 152
Number of unique values for        fbs  :   2
Number of unique values for    restecg  :   3
Number of unique values for    thalach  :  91
Number of unique values for      exang  :   2
Number of unique values for    oldpeak  :  40
Number of unique values for      slope  :   3
Number of unique values for         ca  :   5
Number of unique values for       thal  :   4
Number of unique values for     target  :   2


In [20]:
heart = heart.drop(columns='target', index=range(100,150))
heart

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[253 rows x 13 columns]

### Kidney dataset

In [21]:
kidney = pd.read_csv('kidney_disease.csv', index_col=0)
kidney

age    bp     sg   al   su     rbc        pc         pcc          ba  \
id                                                                           
0    48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1     7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2    62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3    48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4    51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   
..    ...   ...    ...  ...  ...     ...       ...         ...         ...   
395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent   
396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   
397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent   
398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   
399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   

       bgr  ...  pcv    wc   rc  htn   dm cad appet   pe  ane classification  
id          ...                                                               
0    121.0  ...   44  7800  5.2  yes  yes  no  good   no   no            ckd  
1      NaN  ...   38  6000  NaN   no   no  no  good   no   no            ckd  
2    423.0  ...   31  7500  NaN   no  yes  no  poor   no  yes            ckd  
3    117.0  ...   32  6700  3.9  yes   no  no  poor  yes  yes            ckd  
4    106.0  ...   35  7300  4.6   no   no  no  good   no   no            ckd  
..     ...  ...  ...   ...  ...  ...  ...  ..   ...  ...  ...            ...  
395  140.0  ...   47  6700  4.9   no   no  no  good   no   no         notckd  
396   75.0  ...   54  7800  6.2   no   no  no  good   no   no         notckd  
397  100.0  ...   49  6600  5.4   no   no  no  good   no   no         notckd  
398  114.0  ...   51  7200  5.9   no   no  no  good   no   no         notckd  
399  131.0  ...   53  6800  6.1   no   no  no  good   no   no         notckd  

[400 rows x 25 columns]

In [22]:
kidney.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             248 non-null    object 
 6   pc              335 non-null    object 
 7   pcc             396 non-null    object 
 8   ba              396 non-null    object 
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             330 non-null    object 
 16  wc              295 non-null    object 
 17  rc              270 non-null    obj

In [23]:
for col in kidney.columns:
    print('Number of unique values for %14s  : %3d' %(col, kidney[col].nunique()))

Number of unique values for            age  :  76
Number of unique values for             bp  :  10
Number of unique values for             sg  :   5
Number of unique values for             al  :   6
Number of unique values for             su  :   6
Number of unique values for            rbc  :   2
Number of unique values for             pc  :   2
Number of unique values for            pcc  :   2
Number of unique values for             ba  :   2
Number of unique values for            bgr  : 146
Number of unique values for             bu  : 118
Number of unique values for             sc  :  84
Number of unique values for            sod  :  34
Number of unique values for            pot  :  40
Number of unique values for           hemo  : 115
Number of unique values for            pcv  :  44
Number of unique values for             wc  :  92
Number of unique values for             rc  :  49
Number of unique values for            htn  :   2
Number of unique values for             dm  :   5


In [24]:
kidney = kidney.drop(columns='classification', index=range(100,150))
kidney

age    bp     sg   al   su     rbc        pc         pcc          ba  \
id                                                                           
0    48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1     7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2    62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3    48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4    51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   
..    ...   ...    ...  ...  ...     ...       ...         ...         ...   
395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent   
396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   
397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent   
398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   
399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   

       bgr  ...  hemo  pcv    wc   rc  htn   dm cad appet   pe  ane  
id          ...                                                      
0    121.0  ...  15.4   44  7800  5.2  yes  yes  no  good   no   no  
1      NaN  ...  11.3   38  6000  NaN   no   no  no  good   no   no  
2    423.0  ...   9.6   31  7500  NaN   no  yes  no  poor   no  yes  
3    117.0  ...  11.2   32  6700  3.9  yes   no  no  poor  yes  yes  
4    106.0  ...  11.6   35  7300  4.6   no   no  no  good   no   no  
..     ...  ...   ...  ...   ...  ...  ...  ...  ..   ...  ...  ...  
395  140.0  ...  15.7   47  6700  4.9   no   no  no  good   no   no  
396   75.0  ...  16.5   54  7800  6.2   no   no  no  good   no   no  
397  100.0  ...  15.8   49  6600  5.4   no   no  no  good   no   no  
398  114.0  ...  14.2   51  7200  5.9   no   no  no  good   no   no  
399  131.0  ...  15.8   53  6800  6.1   no   no  no  good   no   no  

[350 rows x 24 columns]

### Iris dataset

In [25]:
iris = pd.read_csv('Iris1.csv')
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [26]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [27]:
for col in iris.columns:
    print('Number of unique values for %16s  : %3d' %(col, iris[col].nunique()))

Number of unique values for               Id  : 150
Number of unique values for    SepalLengthCm  :  35
Number of unique values for     SepalWidthCm  :  23
Number of unique values for    PetalLengthCm  :  43
Number of unique values for     PetalWidthCm  :  22
Number of unique values for          Species  :   3


In [28]:
iris = iris.drop(columns='Species', index=range(100,150))
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0     1            5.1           3.5            1.4           0.2
1     2            4.9           3.0            1.4           0.2
2     3            4.7           3.2            1.3           0.2
3     4            4.6           3.1            1.5           0.2
4     5            5.0           3.6            1.4           0.2
..  ...            ...           ...            ...           ...
95   96            5.7           3.0            4.2           1.2
96   97            5.7           2.9            4.2           1.3
97   98            6.2           2.9            4.3           1.3
98   99            5.1           2.5            3.0           1.1
99  100            5.7           2.8            4.1           1.3

[100 rows x 5 columns]