# Basic Python programming concepts
The following programs have been implemented from [Geeks for Geeks](https://www.geeksforgeeks.org/python-programming-examples/).

In [1]:
import numpy as np
import re
import time
import datetime

## Array program
Split an array at specified position and add the first part to the end.

In [2]:
arr = [int(x) for x in input("Enter array values separated by space: ").split(" ")]
n = int(input("Enter position of split: "))

first_split = arr[:n]
new_arr = arr[n:]
new_arr.extend(first_split)

print("\nOld array:", arr)
print("New array:", new_arr)

Enter array values separated by space: 1 2 3 4 5 6 7 8 9 10
Enter position of split: 2

Old array: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
New array: [3, 4, 5, 6, 7, 8, 9, 10, 1, 2]


## List program
Break a list into chunks of size n.

In [3]:
old_list = [int(x) for x in input("Enter values of list separated by space: ").split(" ")]
n = int(input("Enter chunk size: "))

new_list = []
for i in range(0, len(old_list), n):
    temp = old_list[i:i+n]
    new_list.append(temp)

print("Old List:", old_list)
print("New List:", new_list)

Enter values of list separated by space: 1 2 3 4 5 6 7 8 9 10
Enter chunk size: 3
Old List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
New List: [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10]]


## Matrix Program
Adding and Subtracting Matrices.

In [4]:
mat_inp = "Enter values of matrix separated by space for column values and semicolon for rows (eg: 1 2 3;4 5 6): "

matrix1 = [[int(y) for y in x.split(" ")] for x in input(mat_inp).split(";")]
matrix2 = [[int(y) for y in x.split(" ")] for x in input(mat_inp).split(";")]

addition_mat = np.add(matrix1, matrix2)
subtraction_mat = np.subtract(matrix1, matrix2)

print("\nAddition value:\n", addition_mat)
print("\nSubtraction value:\n", subtraction_mat)

Enter values of matrix separated by space for column values and semicolon for rows (eg: 1 2 3;4 5 6): 1 2 3;4 5 6
Enter values of matrix separated by space for column values and semicolon for rows (eg: 1 2 3;4 5 6): 1 2 3;4 5 6

Addition value:
 [[ 2  4  6]
 [ 8 10 12]]

Subtraction value:
 [[0 0 0]
 [0 0 0]]


## String Program
Print even length words in a string.

In [5]:
string_words = input("Enter your string: ").split(" ")

print("\nAll even length words:")
for word in string_words:
    if len(word) % 2 == 0:
        print("%2d %s" % (len(word), word))

Enter your string: This is the python deep learning class

All even length words:
 4 This
 2 is
 6 python
 4 deep
 8 learning


## Dictionary Program
Program to find the sum of all items in a dictionary.

In [6]:
keys = [x for x in input("Enter the keys separated by space: ").split(" ")]
values = [int(x) for x in input("Enter the values separated by space: ").split(" ")]
diction = {i:j for i,j in zip(keys, values)}

print("Sum of values:", sum(values))

Enter the keys separated by space: a b c
Enter the values separated by space: 10 20 30
Sum of values: 60


## Tuple Program
Extract digits from Tuple list.

In [7]:
tuple1 = tuple([int(x) for x in input("Enter values of tuple 1 separated by space: ").split(" ")])
tuple2 = tuple([int(x) for x in input("Enter values of tuple 2 separated by space: ").split(" ")])

res =  [(a, b) for a in tuple1 for b in tuple2]
res = res +  [(a, b) for a in tuple2 for b in tuple1]

print("The filtered tuple : " + str(res))

Enter values of tuple 1 separated by space: 1 2 3
Enter values of tuple 2 separated by space: 5 6
The filtered tuple : [(1, 5), (1, 6), (2, 5), (2, 6), (3, 5), (3, 6), (5, 1), (5, 2), (5, 3), (6, 1), (6, 2), (6, 3)]


## Searching and Sorting Program
Program for Linear Search.

In [8]:
arr = [int(x) for x in input("Enter array values separated by space: ").split(" ")]
x = int(input("Enter item to be found: "))

print(f"Index of element {x} is: {arr.index(x)}")

Enter array values separated by space: 1 9 47 199
Enter item to be found: 9
Index of element 9 is: 1


## Pattern Printing Program
Program to print an Inverted Star Pattern

In [9]:
n = int(input("Enter number of rows you want: "))

for i in range (n, 0, -1):
    print((n-i) * ' ' + i * '*')

Enter number of rows you want: 10
**********
 *********
  ********
   *******
    ******
     *****
      ****
       ***
        **
         *


## Date-Time Program
Convert date string to timestamp in Python

In [10]:
date = input("Enter date (dd): ")
month = input("Enter month (mm): ")
year = input("Enter year (yyyy): ")

string = f"{date}/{month}/{year}"
element = datetime.datetime.strptime(string,"%d/%m/%Y")
timestamp = datetime.datetime.timestamp(element)

print("\nTimestamp:", timestamp)

Enter date (dd): 10
Enter month (mm): 01
Enter year (yyyy): 2022

Timestamp: 1641753000.0


## Python Regex Program
Program to Check if String Contain Only Defined Characters using Regex

In [11]:
def check(str, pattern):
    if re.search(pattern, str):
        print("Valid String")
    else:
        print("Invalid String")

pattern = re.compile("12")
check(input("Enter string to check for pattern (12): "), pattern)

Enter string to check for pattern (12): 12032020
Valid String


## Python File Handling Program
Count number of lines in a text file in Python

In [12]:
with open("sample.txt") as f:
    content = f.readlines()

print("Number of lines in given file:", len(content))

Number of lines in given file: 5
